// <auto-generated />
using System;
using MakerHubAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MakerHubAPI.DAL.Migrations
{
    [DbContext(typeof(CTTDBContext))]
    [Migration("20211109140015_M1")]
    partial class M1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Annonce", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("Annonce");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Competition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategorieAge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassementMaximum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassementMinimum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<TimeSpan>("Heure")
                        .HasColumnType("time");

                    b.Property<string>("Lien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("NombreMax")
                        .HasColumnType("int");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ID");

                    b.ToTable("Competition");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Joueur", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HeureDepartDames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeureDepartHommes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDAFTT")
                        .HasColumnType("int");

                    b.Property<int?>("IDEquipeDames")
                        .HasColumnType("int");

                    b.Property<int?>("IDEquipeHommes")
                        .HasColumnType("int");

                    b.Property<string>("IdentifiantConnexion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Joueur");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.JoueurCompetition", b =>
                {
                    b.Property<int>("IDCompetition")
                        .HasColumnType("int");

                    b.Property<int>("IDJoueur")
                        .HasColumnType("int");

                    b.HasKey("IDCompetition", "IDJoueur");

                    b.HasIndex("IDJoueur");

                    b.ToTable("JoueurCompetition");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.JoueurStage", b =>
                {
                    b.Property<int>("IDStage")
                        .HasColumnType("int");

                    b.Property<int>("IDJoueur")
                        .HasColumnType("int");

                    b.HasKey("IDStage", "IDJoueur");

                    b.HasIndex("IDJoueur");

                    b.ToTable("JoueurStage");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Souper", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<int>("IDType")
                        .HasColumnType("int");

                    b.Property<int?>("NombreMax")
                        .HasColumnType("int");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<double>("PrixAffilies")
                        .HasColumnType("float");

                    b.Property<double>("PrixExternes")
                        .HasColumnType("float");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeSouper")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Souper");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Stage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassementMaximum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassementMinimum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Entraineur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HeureDebut")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("HeureFin")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("NombreMax")
                        .HasColumnType("int");

                    b.Property<double>("PrixAffilies")
                        .HasColumnType("float");

                    b.Property<double>("PrixExternes")
                        .HasColumnType("float");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Stage");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.JoueurCompetition", b =>
                {
                    b.HasOne("MakerHubAPI.DAL.Entities.Competition", "Competition")
                        .WithMany("JoueurCompetitions")
                        .HasForeignKey("IDCompetition")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakerHubAPI.DAL.Entities.Joueur", "Joueur")
                        .WithMany("JoueurCompetitions")
                        .HasForeignKey("IDJoueur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Joueur");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.JoueurStage", b =>
                {
                    b.HasOne("MakerHubAPI.DAL.Entities.Joueur", "Joueur")
                        .WithMany("JoueurStages")
                        .HasForeignKey("IDJoueur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakerHubAPI.DAL.Entities.Stage", "Stage")
                        .WithMany("JoueurStages")
                        .HasForeignKey("IDStage")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joueur");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Competition", b =>
                {
                    b.Navigation("JoueurCompetitions");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Joueur", b =>
                {
                    b.Navigation("JoueurCompetitions");

                    b.Navigation("JoueurStages");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Stage", b =>
                {
                    b.Navigation("JoueurStages");
                });
#pragma warning restore 612, 618
        }
    }
}
