// <auto-generated />
using System;
using MakerHubAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MakerHubAPI.DAL.Migrations
{
    [DbContext(typeof(CTTDBContext))]
    partial class CTTDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Annonce", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("Annonce");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.CategorieAge", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("CategorieAge");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.CategorieInterclubs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("ID");

                    b.ToTable("CategorieInterclubs");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Classement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Denomination")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("ID");

                    b.ToTable("Classement");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Competition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<TimeSpan>("Heure")
                        .HasColumnType("time");

                    b.Property<int>("IDCategorieAge")
                        .HasColumnType("int");

                    b.Property<int>("IDClassementMaximum")
                        .HasColumnType("int");

                    b.Property<int>("IDClassementMinimum")
                        .HasColumnType("int");

                    b.Property<string>("Lien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("NombreMax")
                        .HasColumnType("int");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ID");

                    b.HasIndex("IDCategorieAge");

                    b.HasIndex("IDClassementMaximum");

                    b.HasIndex("IDClassementMinimum");

                    b.ToTable("Competition");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Equipe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<TimeSpan?>("HeureDepart")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HeureMatch")
                        .HasColumnType("time");

                    b.Property<int>("IDCategorieInterclubs")
                        .HasColumnType("int");

                    b.Property<string>("LieuMatch")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("ID");

                    b.HasIndex("IDCategorieInterclubs");

                    b.ToTable("Equipe");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Joueur", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("IDCategorieAge")
                        .HasColumnType("int");

                    b.Property<int?>("IDClassementDames")
                        .HasColumnType("int");

                    b.Property<int>("IDClassementHommes")
                        .HasColumnType("int");

                    b.Property<int?>("IDEquipeDames")
                        .HasColumnType("int");

                    b.Property<int?>("IDEquipeHommes")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("IDCategorieAge");

                    b.HasIndex("IDClassementDames");

                    b.HasIndex("IDClassementHommes");

                    b.HasIndex("IDEquipeDames");

                    b.HasIndex("IDEquipeHommes");

                    b.ToTable("Joueur");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.JoueurCompetition", b =>
                {
                    b.Property<int>("IDCompetition")
                        .HasColumnType("int");

                    b.Property<int>("IDJoueur")
                        .HasColumnType("int");

                    b.HasKey("IDCompetition", "IDJoueur");

                    b.HasIndex("IDJoueur");

                    b.ToTable("JoueurCompetition");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.JoueurStage", b =>
                {
                    b.Property<int>("IDStage")
                        .HasColumnType("int");

                    b.Property<int>("IDJoueur")
                        .HasColumnType("int");

                    b.HasKey("IDStage", "IDJoueur");

                    b.HasIndex("IDJoueur");

                    b.ToTable("JoueurStage");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Souper", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<int>("IDType")
                        .HasColumnType("int");

                    b.Property<int?>("NombreMax")
                        .HasColumnType("int");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<double>("PrixAffilies")
                        .HasColumnType("float");

                    b.Property<double>("PrixExternes")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("IDType");

                    b.ToTable("Souper");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Stage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Entraineur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("time");

                    b.Property<int>("IDClassementMaximum")
                        .HasColumnType("int");

                    b.Property<int>("IDClassementMinimum")
                        .HasColumnType("int");

                    b.Property<int?>("NombreMax")
                        .HasColumnType("int");

                    b.Property<double>("PrixAffilies")
                        .HasColumnType("float");

                    b.Property<double>("PrixExternes")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("IDClassementMaximum");

                    b.HasIndex("IDClassementMinimum");

                    b.ToTable("Stage");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.TypeSouper", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.ToTable("TypeSouper");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Competition", b =>
                {
                    b.HasOne("MakerHubAPI.DAL.Entities.CategorieAge", "CategorieAge")
                        .WithMany("Competitions")
                        .HasForeignKey("IDCategorieAge")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MakerHubAPI.DAL.Entities.Classement", "ClassementMaximum")
                        .WithMany("CompetitionsMax")
                        .HasForeignKey("IDClassementMaximum")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MakerHubAPI.DAL.Entities.Classement", "ClassementMinimum")
                        .WithMany("CompetitionsMin")
                        .HasForeignKey("IDClassementMinimum")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CategorieAge");

                    b.Navigation("ClassementMaximum");

                    b.Navigation("ClassementMinimum");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Equipe", b =>
                {
                    b.HasOne("MakerHubAPI.DAL.Entities.CategorieInterclubs", "CategorieInterclubs")
                        .WithMany("Equipes")
                        .HasForeignKey("IDCategorieInterclubs")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategorieInterclubs");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Joueur", b =>
                {
                    b.HasOne("MakerHubAPI.DAL.Entities.CategorieAge", "CategorieAge")
                        .WithMany("Joueurs")
                        .HasForeignKey("IDCategorieAge")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakerHubAPI.DAL.Entities.Classement", "ClassementDames")
                        .WithMany("JoueursDames")
                        .HasForeignKey("IDClassementDames");

                    b.HasOne("MakerHubAPI.DAL.Entities.Classement", "ClassementHommes")
                        .WithMany("JoueursHommes")
                        .HasForeignKey("IDClassementHommes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakerHubAPI.DAL.Entities.Equipe", "EquipeDames")
                        .WithMany("JoueursDames")
                        .HasForeignKey("IDEquipeDames");

                    b.HasOne("MakerHubAPI.DAL.Entities.Equipe", "EquipeHommes")
                        .WithMany("JoueursHommes")
                        .HasForeignKey("IDEquipeHommes");

                    b.Navigation("CategorieAge");

                    b.Navigation("ClassementDames");

                    b.Navigation("ClassementHommes");

                    b.Navigation("EquipeDames");

                    b.Navigation("EquipeHommes");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.JoueurCompetition", b =>
                {
                    b.HasOne("MakerHubAPI.DAL.Entities.Competition", "Competition")
                        .WithMany("JoueurCompetitions")
                        .HasForeignKey("IDCompetition")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakerHubAPI.DAL.Entities.Joueur", "Joueur")
                        .WithMany("JoueurCompetitions")
                        .HasForeignKey("IDJoueur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Joueur");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.JoueurStage", b =>
                {
                    b.HasOne("MakerHubAPI.DAL.Entities.Joueur", "Joueur")
                        .WithMany("JoueurStages")
                        .HasForeignKey("IDJoueur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakerHubAPI.DAL.Entities.Stage", "Stage")
                        .WithMany("JoueurStages")
                        .HasForeignKey("IDStage")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joueur");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Souper", b =>
                {
                    b.HasOne("MakerHubAPI.DAL.Entities.TypeSouper", "TypeSouper")
                        .WithMany("Soupers")
                        .HasForeignKey("IDType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeSouper");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Stage", b =>
                {
                    b.HasOne("MakerHubAPI.DAL.Entities.Classement", "ClassementMaximum")
                        .WithMany("StagesMax")
                        .HasForeignKey("IDClassementMaximum")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MakerHubAPI.DAL.Entities.Classement", "ClassementMinimum")
                        .WithMany("StagesMin")
                        .HasForeignKey("IDClassementMinimum")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ClassementMaximum");

                    b.Navigation("ClassementMinimum");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.CategorieAge", b =>
                {
                    b.Navigation("Competitions");

                    b.Navigation("Joueurs");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.CategorieInterclubs", b =>
                {
                    b.Navigation("Equipes");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Classement", b =>
                {
                    b.Navigation("CompetitionsMax");

                    b.Navigation("CompetitionsMin");

                    b.Navigation("JoueursDames");

                    b.Navigation("JoueursHommes");

                    b.Navigation("StagesMax");

                    b.Navigation("StagesMin");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Competition", b =>
                {
                    b.Navigation("JoueurCompetitions");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Equipe", b =>
                {
                    b.Navigation("JoueursDames");

                    b.Navigation("JoueursHommes");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Joueur", b =>
                {
                    b.Navigation("JoueurCompetitions");

                    b.Navigation("JoueurStages");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.Stage", b =>
                {
                    b.Navigation("JoueurStages");
                });

            modelBuilder.Entity("MakerHubAPI.DAL.Entities.TypeSouper", b =>
                {
                    b.Navigation("Soupers");
                });
#pragma warning restore 612, 618
        }
    }
}
